version: "3.9"

services:

  web:
    build: .
    container_name: web
    command: uvicorn main:app --host 127.0.0.1 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:7.0"
    container_name: RedisTest
    ports:
      - "6379:6379"